name: Integration Tests 06

on: [push, pull_request]

jobs:
  build:
    name: tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
        deno: ["v1.4.6", "v1.4.4"]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      - name: run tests
        run: deno test -c tsconfig.json --reload --allow-all --unstable --filter "IT06" tests/integration-tests/