name: PG Driver Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macOS-latest]
        deno: ["v1.2.3"]
      fail-fast: true    

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_PASSWORD: Changeme1
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.47.0
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-
      # Build
      - name: Build
        run: cd rust-core && cd database && cd drivers && cd postgres && cargo build --release --locked --all-targets  
      - uses: actions/checkout@v2
      - name: Setup deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      - name: run tests
        run: deno test -c tsconfig.json --reload --allow-all --unstable tests/db-tests/  
    